[toolchain]
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
todo = "EPFBi5maMUcdV3rYj2yssVAhNwAK4nxqjqreML96ubcf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/freeCodeCampWeb3/solana-curriculum/tutorials/todo.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
